### ISSUE TITLE
Review conflicting approaches to public data and design best path

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#103]
# Approach 1
Approach 1 is to have a superclass of each bob with the word "public" in its name that only includes the fields we want to release to the public. This exists for Property objects as shown below:

![Screenshot_2020-06-22_10-06-03](https://user-images.githubusercontent.com/10214958/85297441-c0ab2580-b470-11ea-86f9-318a96d6141f.png)

# Approach 2: Public info bundle
In a separate class hierarchy, with `PublicInfoBundle` at its base. Because this is a separate hierarchy, there is less risk of accidentally releasing fully data-ified objects to the public, but the downside is it's less flexible because that object heierarchy is not accepted anywhere internally. 

This is used in the CECase example
![image](https://user-images.githubusercontent.com/10214958/85297672-0bc53880-b471-11ea-8d37-887ee0c04140.png)

## Task order

0. Start a logical branch for all these changes, like publicportalupgrade
1. Which is best? We probably want a unified approach across all business objects.
2. Try out your approach with Person and Property (these represent both approaches) and work out kinks before we extend to OccPeriod and OccApplication and Permit
3. Please attempt some rudimentary documentation of the approach in the ss_publicInfoBundle.md file on the MASTER branch

**Comment by NADGIT** [comment]
I posted some documentation on my unified approach yesterday, and started implementing it in the code today. I'll have public info bundles of persons and property hopefully by the end of the day!

**Comment by NADGIT** [comment]
Bundled Person complete! Took longer than I thought, there's alot of fields in the Person object!

**Comment by NADGIT** [comment]
I've completed BundledProperties too. I will keep this issue open as I continue to perfect this new PublicInfoBundle system, but for now I will move on to #75

**Comment by NADGIT** [comment]
I just finished a ton of changes to the bundling and un-bundling process that are on the publicPortalUpgrade branch. At the moment, the following classes have bundles:

- CEActionRequests
- CECases
- FeeAssigneds (applies to both subclasses)
- OccInspections
- OccPeriods
- Payments
- Persons
- Properties

If there are any more bundles or changes needed, please reply here

**Comment by NADGIT** [comment]
Bundles that still need completed:

1. PropertyUnit (with Bundled OccPeriod List)
2. EventCnF

And any bundles these objects might need. Will continue on new branch

**Comment by NADGIT** [comment]
These bundles are complete, and just got pushed up in the publicPortalUpgradePhaseTwo branch.

**Comment by edarsow** [comment]
Great, thanks @NADGIT
