### ISSUE TITLE
Snappers linux learning ideas

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#104]
Some tasks to learn to do on Linux
* Digest all available information given with the `ls -al` command: permissions settings, user/group, etc.
* Create plain files, like text files, and change their owner, group, and permissions for each level: user, group, and other | this will involve using the `chown` and `chmod` commands
* Learn to digest the output of `htop` which is the system monitor
* Learn to digest the output of `ps -aux` command which lists all processes and learn to find a process using the `ps -aux | grep xxx` and killing a process. Try starting a process, finding it running with the `ps -aux` and try killing it with `kill [pid]`
* Read about the `/etc/hosts` file and make an entry for the COGSERVER on your local machine's `/etc/hosts` so that you can say something like `ssh snapper@cogserver` and the system will automatically look up the IP address for the host you named 'cogserver'
* Learn how to get files onto the server from another system: Option 1 is to use the secure copy command that is basically an extension of ssh for moving a single file. This tool is called `scp` and you could start with the man page. Option 2 is to connect to the sever using filezilla and the sftp command. here is a screen shot of Eric's filezilla setup for connecting to the server
![image](https://user-images.githubusercontent.com/10214958/85422804-0127a380-b544-11ea-9471-79fd4cf1e588.png)
* Practice moving a python file from your local machine to the server and running it in a properly configured python environment
* Then, start digging into the python environments on the server. Add yourself to the `python` group on the server and see that you can run stuff as either the `snapper` user or the `python` user
* Check on the `cron` setup on the server and try creating a python script that will run periodically and add evidence of that running in a text file whose permissions are sensibly set to be as restrictive as possible
* Attempt to connect to the remote database via ssh tunneling which is made with this command
`ssh -f [user]@[host] -L 20000:localhost:5432 -N`
this says: connect MY local port 20000 to the remote port 5432 (the remote postgres will still only listen on localhost:5432 -- the SSH tool on the remote system will make all the necessary adjustments to the incoming packets to make them look local to its host system). Note: You'll run this command on your local shell -- nothing needs to be run on the remote system. Once you run this command locally, you'll setup a new connection in PGAdmin to a server on the localhost:20000 (or whatever port over 1023 you choose)

**Comment by snapperVibes** [comment]
Whack. I will have plenty to look forward to. Thank you!
