### ISSUE TITLE
Transition away from scraping county data into API calls

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#106]
Based on SNAPPER's work investigating the API situation and the WPRDC, the need for scraping from the county's assessment page in HTML has been obviated. This issue broadly tasks the tackler with replacing the scraping script portions with API calls against the WPRDC resources exposed therein.

This involves deciding which should be the SQL API, the raw URL string, and processing the sale data flat file.

**Comment by snapperVibes** [comment]
Forgot to close this earlier.
