### ISSUE TITLE
Public info coordinator facelift

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#110]
With our work on the public side commencing, please add javadoc style comments to each method in the `PublicInfoCoordinator` that reflects NADGIT's choices around the unified approach to public info bundle filter/setter methods.

**Comment by NADGIT** [comment]
I just completed the facelift. It should be in the branch publicPortalUpgradePhaseTwo, but I'm keeping this issue up in case the documentation needs to change.

**Comment by edarsow** [comment]
Comment look good, thanks NADGIT!
