### ISSUE TITLE
Upgrade public pages and workflows to new UI designed by Chen&Chen

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#111]
# Step 1: Assess the situation
Review existing workflows for the public services we're aiming to beta test on 15 July. Notes exist below, but stuff is in decent shape file wise and lives in the public directory and its subdirs
![image](https://user-images.githubusercontent.com/10214958/86386506-d6ce9800-bc5f-11ea-895a-92f4e9aad6aa.png)

1. **CEactionRequest Submission by public**: The public can create an issue and submit it for code officer review. It currently exists as one of the more bug-free multi-page workflows in codeNforce. There was actually a short time that Churchill's office staff was actually using the utility to submit requests. The code officer wouldn't use the back end, so that was how that went.

The pages exist but have old wiring, potentially to fields that don't exist on the business objects anymore. See the longer explanation for calls to `SessionBean` from the faces pages on the OccApp below. This is is a dreaded "anti-pattern".

![image](https://user-images.githubusercontent.com/10214958/86387016-8c015000-bc60-11ea-85af-26e307c18ed4.png)

2. Occupancy Applications: Public users can search for a a property, check its unit list, made edits to unit list, and begin the occupancy permitting process by saying: "I want to rent unit 3A at 234 Main St". For Beta, only the application can be submitted online--all other functions are internal only 

The pages exist but the wiring to backing beans needs to be revisited. On a first glance, I see a lot of direct calls to the `SessionBean` on the faces page, which we aren't doing by pattern. Rather, if we need a session object, it should be put on a member by the view-scoped backing bean. Don't forget the handy `SystemServicesBB` which exposes key session objects like `UserAuthorized` and `OccPeriod`.

![image](https://user-images.githubusercontent.com/10214958/86386804-40e73d00-bc60-11ea-9dd8-e10baf102ba3.png)

# Step 2: Prioritize fixes
The key fix is we need all the pages to conform to the sample UI from Chen&Chen located in the files below:
![image](https://user-images.githubusercontent.com/10214958/86385972-1c3e9580-bc5f-11ea-9d0e-cb602f6ceffa.png)

After reviewing the status of our system, create sensible issues based on stuff that isn't done, or is broken. Discuss with ECD which changes/additions we should prioritize first.

# Step 3: Navigation verification
Verify existing links on the public facing pages to our public facing utilities. Use the navigation system designed by Chen&Chen for this process: check the `SystemCoordinator` for essential navigation methods. A note on Nav: The Chen&Chen model bypasses the `faces-config.xml` nav system built into JSF 1 by baking the fully-qualified page URL into the method's `String` return type which gets fed directly into the navigator on the server. You can use this new approach or `faces-config.xml` since they are both officially supported in codeNforce v.0.9

# Step 4: Security
1. Revisit captcha stuff
2. Strip photos of meta-data
3. SQL injection revisiting

# Step 5: Internal management of public utilities
Review and CREATE necessary upgrades to restricted pages that manage data/objects created on the public side, including turning on and off PACC functions for various subsystems and object-specific switches (i.e. a single case or CEActionRequest can have its PACC turned off, but we also want a municipality to be able to turn off ALL public access to any one of our public utilities.

The most comprehensive existing management page is the CEActionRequests.xhtml which allows for searching by pre-built query and routing the CEAR to any one of four pathways using buttons 
![image](https://user-images.githubusercontent.com/10214958/86384878-5c9d1400-bc5d-11ea-9fd5-8581031680ff.png)

I think NADGIT built a review page for the occ app changes?

# Step 6: Documentation
## For users: 
Write some simple how-to's for training COG staff on how the system work from a front and back end so they can, in turn, train municipalities
## For devs: 
Using our standard documentation tool, make necessary pages targeted at developers specifically

**Comment by NADGIT** [comment]
Tackling this issue now!

**Comment by NADGIT** [comment]
The existing Request Code Enforcement workflow is now up and running again! I'll ask at tomorrow's meeting what needs to be done next.

**Comment by NADGIT** [comment]
The CE Action Request workflow has been upgraded to the new UI! Time to fix the occupancy pages!

**Comment by NADGIT** [comment]
I did some reading on SQL injections and security. It seems like we're mostly good:

https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html

https://security.stackexchange.com/questions/15214/are-prepared-statements-100-safe-against-sql-injection

Apparently using prepared statements (as we do) prevents most SQL injection attacks. We could probably be even more safe, but I think we're safe enough for launch.

**Comment by NADGIT** [comment]
Also, navigation is all good - you can get to all pages correctly. It uses the old faces-config style navigation, but right now I'm just trying to prioritize everything else.

**Comment by NADGIT** [comment]
Steps 1-3 are sorta complete. The public pages are fully functional, however the Occupancy Permit Application workflow was not converted to the Chen UI as per time constraints.

I'm jumping to step 5. Our public portals aren't much use if Code Officers can't respond to public requests.

**Comment by NADGIT** [comment]
The changes on pull request #139 Should complete the CE Request management workflow! Next is Occ!

**Comment by NADGIT** [comment]
The OccPermitApplicaton workflow was complete as of pull request #152. Also, new objective: add back buttons to public pages using NavStack

**Comment by NADGIT** [comment]
Once my Change order pages are complete, I will work to address the improvements that Tim suggested. It's all written up in issue #158

**Comment by NADGIT** [comment]
Change orders complete! Also, I think @Xiaohong-Chen fixed most if not all of #158, but I'll check to make sure. If it is finished, I'll close it after attached a comment about where credit is due.

**Comment by NADGIT** [comment]
I fixed some errors with Occ Permit Application workflow in #167. More info on it there. I'll be moving onto #112!
