### ISSUE TITLE
PACC upgrades

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#112]
# For Phase 2: Upgrade PACC strategy to include occupancy applications
Since we're no longer using a text blob approach to viewing public info, and are instead interacting with the objects in our patterned way, we'll need to rework the entire page/approach and bake in occupancy application lookup by PACC.

To your point, please make sure that the PACC number applies to all relevant objects. And remember, on CECase object there's a boolean switch that allows folks with only a PACC that applies to the CEActionRequest to also get any related Case objects that were created based on that action request. (It's called allowuplinkaccess)
![image](https://user-images.githubusercontent.com/10214958/86368746-864d3f80-bc4b-11ea-91f3-251903de4327.png)

**Comment by NADGIT** [comment]
When I do begin to make these upgrades, I need to remember that right now that the occpermitapplication table may have a column for occperiodid, but it's not being used yet. I probably need to link it to an occperiod automatically.

**Comment by NADGIT** [comment]
I completed the PACC viewing pages for CE and OCC last week and today I've begun the debugging and polishing.

**Comment by NADGIT** [comment]
I have finished debugging and polishing the PaccView pages. They'll be packaged in a pull request with some fixes to other public pages.

**Comment by NADGIT** [comment]
I've finished these interfaces, will link this issue to the corresponding pull request.
