### ISSUE TITLE
Upgrade search tools for public pages to use new Parameter system

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#114]
Now that we have upgraded search tools, please upgrade the public system to use this model:

Here's a sample method that initializes a QueryProperty, extracts and customizes is SearchParamProperty internal object for SQL statement building, and then sends off the configured QueryProperty to the `SearchCoordinator`'s runQuery() method:

![image](https://user-images.githubusercontent.com/10214958/86603719-5e731a00-bf72-11ea-89e3-ef26aec452d2.png)

**Comment by NADGIT** [comment]
I'm going to fix the Property Search now. It shouldn't take too long but I'll keep this issue open as I think there might be people searches and another property search for Occ.

**Comment by NADGIT** [comment]
I also had to update the person and property search for Occ. I completed it last night but it is untested. I'm leaving this issue up until I'm sure there is no more work to complete on searches.

**Comment by NADGIT** [comment]
Now that I've completed the public portals, I can safely say there are no more public searches to implement.
