### ISSUE TITLE
CEAction Request datum/label CSS mess

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#121]
Dear Chen&Chen,

Could you take a look at the requestCEActionFlow_requestorDetails.xhtml page shown below to help figure out why the data and the labels are all out of sorts? NADGIT and I discovered this while testing. 

And, perhaps you could provide some design ideas for the overall action request submission page? Please phone NADGIT with questions.

![Screenshot_2020-07-10_10-10-41](https://user-images.githubusercontent.com/10214958/87431143-39a32600-c5b4-11ea-8c2b-3e6328d766dc.png)

**Comment by Xiaohong-Chen** [comment]
I checked the code from publicPortalUpgradePhaseTwo branch. It is the <h3> tag that mess up the page. Getting the <h3>Requestor:</h3>  out of  <div class="ui-g data-container"> and everything will turn to normal.

![Screenshot_2020-07-14_11-52-14](https://user-images.githubusercontent.com/37033896/87447971-37979200-c5c9-11ea-96bd-e17768c7c53a.png)

![Screenshot_2020-07-14_11-58-17](https://user-images.githubusercontent.com/37033896/87448087-5c8c0500-c5c9-11ea-94ad-bed7ae34dcc0.png)

**Comment by Xiaohong-Chen** [comment]
I checked the code from publicPortalUpgradePhaseTwo branch. It is the <h3> tag that mess up the page. Getting the <h3> Requestor:</h3> out of <div class="ui-g data-container"> and everything will turn to normal.

![Screenshot_2020-07-14_11-52-14](https://user-images.githubusercontent.com/37033896/87448972-8db90500-c5ca-11ea-8a0a-1ff39b6eb712.png)

![Screenshot_2020-07-14_11-58-17](https://user-images.githubusercontent.com/37033896/87448987-914c8c00-c5ca-11ea-92d1-25488b9350b2.png)

**Comment by Xiaohong-Chen** [comment]
I checked the code from publicPortalUpgradePhaseTwo branch. It is the `<h3>` tag that mess up the page. Getting the `<h3> Requestor:</h3> ` out of  `<div class="ui-g data-container">` and everything will turn to normal.

![Screenshot_2020-07-14_11-52-14](https://user-images.githubusercontent.com/37033896/87449098-bb05b300-c5ca-11ea-9f62-b57e992ad982.png)

![Screenshot_2020-07-14_11-58-17](https://user-images.githubusercontent.com/37033896/87449103-bccf7680-c5ca-11ea-8934-07cd8d06358c.png)

**Comment by NADGIT** [comment]
Done! Fix is in #126
