### ISSUE TITLE
Review changes to PublicInfoBundleCECase

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#140]
Dear NADGIT, 

EDDIE had to remove a `List<EventCnF>` member var on the `CECasePropertyUnitHeavy` due to an inheritance and object retrieval authorization pathway mess. EDDIE had to comment out some chunks of this code; please review and consult as needed. You may need to get a data heavy case instead, which is where the event list went;
![image](https://user-images.githubusercontent.com/10214958/88157087-4ccb7c80-cbd8-11ea-8950-16d16a4aadb5.png)

**Comment by NADGIT** [comment]
I've addressed this while finishing up PACC stuff. It's all working again!
