### ISSUE TITLE
Pathways of occPermitApplications

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#143]
As a mirror to CEARs, the occ permit applications can be routed as follows:

1. Spawn a new occ period on an existing property unit (i.e. not a new one created during this occapp's session)
2. Spawn a new occ period on a new property unit (in this case, the user will need to approve and authorize the existence of the new unit BEFORE the spawning can occur, because we don't want to end up with the period attached to a spurious unit and which we then have to reconnect later to the correct object). Please exercise NADGIT-level care in designing this sequence, as usual.
3. The application is duplicated or has been rejected by the officer. This is not quite "delete" but rather "processed but not action taken"
3. The application is spurious and will result in no official object changes on the restricted side; in this case, we want this to be as close to "delete" as we get

NOTE: The third case in which the occ app is basically "rejected" will need to be more thoroughly planned for phase 2 when users will want to visit the site to check on the status of their occapplication. If it's in deactivated, we shouldn't be accessing it at all.

**Comment by NADGIT** [comment]
All of these pathways of Occupancy are implemented! Will come with next pull request
