### ISSUE TITLE
Event Category name

### ISSUE THREAD

**Issue by snapperVibes** [TechnologyRediscovery/codenforce#156]
I wrote a script to compare the most recent data from the WPRDC API and the database. If any properties appear in the database that do not appear in WPRDC API, it will write an Event to the database (to eventually be seen by the code officers).

I'm drawing blanks on a descriptive name for the event. The best I have so far is `ParcelNotInRecentRecords`, which I do not think is very good.

Once I have a name, I'll write sql to insert the event category into the database. Does the Java side need to know about new event categories, or are all events handled the same way?

**Comment by edarsow** [comment]
Addressed in grant deliverables
