### ISSUE TITLE
Public Portal facelift

### ISSUE THREAD

**Issue by NADGIT** [TechnologyRediscovery/codenforce#158]
I've received some feedback on my public portal pages from Tim, and I'd like to get started on it soon. I have a copy of the email I received saved in a word doc, but I'm going to type up a simplified version here so I can track my progress once I get to work on it.

- [ ]  1. There are too many buttons, and there should be only two button styles: blue for the primary actions and gray for secondary actions (e.g. canceling). There are also some buttons in the sidebar that only people with a login should see.

- [x]  2. The buttons at the bottom should be consistent. "Next Step: XXXXX"

- [x]  3. Make sure that term used in the interface remain consistent instead of switching between synonyms every page.

- [x]  4. To make tabbing easier, put text entry fields before buttons and clickable fields.

- [x]  5. Remove extraneous labels.

- [ ]  6. "My mockups also suggest keeping consistency with fields…some were in accordions, etc. and that adds to the clutter." - Tim

- [x]  7. Increase the font of the "next step" buttons.

Here is the example drawn up by Tim:

![image](https://user-images.githubusercontent.com/46534741/89938987-4a5faf80-dbe5-11ea-9ad4-12116ab46f74.png)

**Comment by edarsow** [comment]
Excellent
