### ISSUE TITLE
propertyperson creation time stamp

### ISSUE THREAD

**Issue by snapperVibes** [TechnologyRediscovery/codenforce#171]
# The issue
The `propertyperson` table does exactly what it says it does; It links a property to a person.
However, it does **not** tell who the current owner of the property is; it just provides a list of properties and any person[*](#footnotes) at one point who owner it.

# The solution
Adding a creation time stamp column to the `propertyperson` table. The new column allows us to infer the current owner by sorting propertyperson by creationts and selecting the most recent entry. Note that it does not tell us the owner for sure, as the WPRDC only updates once a month.

# Database Side
Before any other code is merged into `recovered`, it is important `propertyperson_ts.sql` is run (which will be added soon to the patch folder). Otherwise the application will break.

There should be consideration for adding a not null constraint on the new `creationts` column. If we are feeling fancy, I can write a script that updates `creationts` to be equal to the creation timestamp of the corresponding property or person, whichever was created most recently.  Otherwise we can set it to a default value.

# Java Side
The Java side needs to add a time stamp attribute to the class `PropertyPersonsBB`.

The method `getFilteredPersonList` ought to sort the people such that the most recent is the newest.

Consider adding the method 'getMostRecentPerson'.

### Footnotes
<span id=footnotes>*</span> Person is a misnomer, as an entity (such as a trust or LLC) is counted. Refactoring the word person out of our code and database is a large project that is not worth doing at this time.

**Comment by snapperVibes** [comment]
#172

**Comment by edarsow** [comment]
Baked into humanization
