### ISSUE TITLE
Scrape all of Lincoln parcels onto live db

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#18]
Lincoln Borough exists in the live system, but is home to only one parcel, the Lincoln Borough office. Please scrape the rest from the county so all is up-to-date

**Comment by matts207** [comment]
On it :)  I missed python so much...

**Comment by edarsow** [comment]
Unknown status on this--redirecting to SNAPPERS

**Comment by edarsow** [comment]
Delayed
