### ISSUE TITLE
Occ workflow resurrection

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#192]
# Goal
Resurrect public occupancy permit application pages located in public/services/occPermitApplicationFlow. This will likely require fixing a few incompatible components from the primefaces 6.0 to primefaces 10.0 upgrade, 

## text editor fixes
`<p:editor>` must be changed to the new component <p:textEditor> and the secure flag must be `false` so the component should look like this:
```xml
   <p:textEditor   id="cecase-notes-editor"
                                            value="#{ceCaseSearchProfileBB.formNoteText}"
                                            required="false"
                                            secure="false"
                                            height="200"/>
```
## file upload component deprecated
Eric's working on image upload stuff last week in May. These will cause errors, so remove them completely from pages and leave a comment where they came out
```xml
 <p:fileUpload fileUploadListener="#{uploadBlobBB.handleBlobUpload}"
                                mode="advanced" 
                                update=":uploadBlobReviewBlobsForm:blobTable"
                                multiple="true"
                                sizeLimit="900000000" 
                                allowTypes="/(\.|\/)(jpe?g|png|pdf)$/"/>    
```

## Lay of the land
The public occupancy permit application pages are mostly serviced by `OccPermitApplicationBB`. The internal page for reviewing the submitted public applications is called `occPermitApplications`. The purpose of the internal page is to allow the code officer to review submitted data and update the object connections made by the public user, such as the associated property, property unit, persons, etc.

## Fix `occPermitApplications`
This is an old page that needs a PF 10.0 upgrade, including the removal the old layout tool called <p:panelGrid> and replacing it with the flex box tool in PF 10 called [flex grid](http://primefaces.org/showcase/primeflex/grid.xhtml?jfwid=59d33). See this used in action on our `ceCaseProfile` page. The flex boxes are implemented with these divs:

```xml
<div class="ui-g data_container_nested_restrict">
                                                <div class="ui-g-12 ui-md-12 ui-lg-12 restrict-data-field">
                                                    <div class="restrict-data-field-label-inline" >
```
## Model internal `occPeriodWorkflow.xhtml` page against `ceCaseProfile.xhtml`
You'll notice there are a bunch of pages inside restricted/cogstaff/occ that are prefixed `occPeriodXXX` that were intended to manage a single object associated with a given OccPeriod. These need to be collapsed like the `ceCaseProfile.xhtml` page such that each sub-object inside an `OccPeriod` has its own `<p:panel>`. These will be inside a big flex box:

```xml


                            <div class="ui-g data_container_nested_restrict">
                                <div class="ui-g-12 ui-md-6 ui-lg-6 restrict-data-field">

                                    <p:panel    id="cecase-profile-panel"
                                                toggleable="true"
                                                widgetVar="cecase-profile-panel-var"
                                                collapsed="false"
                                                rendered="true"
                                                header="Code Enforcement Case | ID: #{ceCaseSearchProfileBB.currentCase.caseID} | last updated: #{ceCaseSearchProfileBB.getPrettyDateNoTime(ceCaseSearchProfileBB.currentCase.lastUpdatedTS)}">
``

**Comment by edarsow** [comment]
I think we're all set on this one, thanks JURPLEL

**Comment by jurplel** [comment]
:+1:
