### ISSUE TITLE
PyParcel

### ISSUE THREAD

**Issue by snapperVibes** [TechnologyRediscovery/codenforce#205]
Just checking in and making sure PyParcel is still running smoothly.

**Comment by edarsow** [comment]
Hi SNAPPERS, We are in the middle of migration to humanization tables, which is I think where PyParcel left off. I don't see any updated records in propertyexternaldata: the last update was DEC-6-2020. Does that sound right? Let's meet up soon.

**Comment by edarsow** [comment]
moved to gaze llc
