### ISSUE TITLE
Occupancy inspection revisions

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#207]
Make OccSpaceType do all the things that OccSpace does.
OccInspectedSpace has an OccSpaceType inside it
ECD to Revise database and objects Tuesday.

**Comment by edarsow** [comment]
NOTE that ECD just pushed a new commit to [recovered that contains db patch 35.1](https://github.com/TechnologyRediscovery/codenforce/blob/recovered/codeconnect/database/patches/dbpatch_beta35.1.sql) with oodles of occ changes in the DB, but NO changes in JavaJava land have happened yet. A bunch of new methods will be needed for the various utility tables required by the specs from Emily and Sean. Until soon!

**Comment by edarsow** [comment]
Implementation Notes for Patch 35.1

# Start with creating new Java objects and integration methods on `InspectionIntegrator` to implement the occ inspection specs

- Utility object called `OccInspectionCause` with members that map to those on the table `occinspectioncause`. Then make `INSERT` and `UPDATE` methods on the integrator. Also include a method that returns all records in this table whose active field is TRUE
- Utility object called `OccInspectionDetermination` with members that map to those on the table `occinspectiondetermination` Then make `INSERT` and `UPDATE` methods on the integrator. Also include a method that returns all records in this table whose active field is TRUE
- Utility object called `OccInspectionDetermination` with members that map to those on the table `occinspectiondetermination` Then make `INSERT` and `UPDATE` methods on the integrator. Also include a method that returns all records in this table whose active field is TRUE

# Rewire business objects
## update notes
- Per the script, the table `occspace` is gone, and `occspaceelement` now has a FK to `occspacetype`.
- Overly complex logic fields were dropped from `occchecklistspacetype`. The corresponding members need to be removed and integrator methods updated to work
- Note that we have a new many:many table called `occchecklistspacetype`  which allows us to say "commerical checklists have space types of something like `high voltage electrical utility` and `fire closet` whereas residential only has `and 'ocespacetypeelement`   -- keep going ECD

**Comment by edarsow** [comment]
In the meantime occ inspection is now a beast!
So we can start with upgrading the integration and member variable that insert and update OccInspection objects. Note that they now have additional fields, notably an Occ Inspection should have int type field for an inspection of which it is a "follow up inspection" (not an a pointer to a whole new inspection object to avoid cycle risk"

You could go ahead and make an `OccInspectionCause` and `OccInspectionDetermination` java class, one instance of each of which will be inside each occ inspection. We'll need drop-down lists on the UI to select the cause and determination as converter methods that echo `PropertyUseTypeConverter`. 

Notes:
- There are three determination fields, one for the determination record KEY, one for the timestamp of when that field was keyed, and by which user.

```

CREATE TABLE public.occinspection
(
  inspectionid integer NOT NULL DEFAULT nextval('occupancyinspectionid_seq'::regclass),
  occperiod_periodid integer NOT NULL,
  inspector_userid integer NOT NULL,
  publicaccesscc integer,
  enablepacc boolean DEFAULT false,
  notespreinspection text,
  thirdpartyinspector_personid integer,
  thirdpartyinspectorapprovalts timestamp with time zone,
  thirdpartyinspectorapprovalby integer,
  maxoccupantsallowed integer NOT NULL,
  numbedrooms integer,
  numbathrooms integer,
  occchecklist_checklistlistid integer,
  effectivedate timestamp with time zone,
  active boolean DEFAULT true,
  creationts timestamp with time zone,
  followupto_inspectionid integer, 
  timestart timestamp with time zone,
  timeend timestamp with time zone,
  determination_detid integer,
  determinationby_userid integer,
  determinationts timestamp with time zone,
  remarks text,
  generalcomments text,
  CONSTRAINT occinspection_pk PRIMARY KEY (inspectionid),
  CONSTRAINT occinpection_determinationby_fk FOREIGN KEY (determinationby_userid)
      REFERENCES public.login (userid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_checklistid_fk FOREIGN KEY (occchecklist_checklistlistid)
      REFERENCES public.occchecklist (checklistid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_determination_fk FOREIGN KEY (determination_detid)
      REFERENCES public.occinspectiondetermination (determinationid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_followupto_fk FOREIGN KEY (followupto_inspectionid)
      REFERENCES public.occinspection (inspectionid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_inspector_userid_fk FOREIGN KEY (inspector_userid)
      REFERENCES public.login (userid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_periodid_fk FOREIGN KEY (occperiod_periodid)
      REFERENCES public.occperiod (periodid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspection_thirdpartyuserid_fk FOREIGN KEY (thirdpartyinspector_personid)
      REFERENCES public.person (personid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT occinspectionthirdpartyapprovalby_fk FOREIGN KEY (thirdpartyinspectorapprovalby)
      REFERENCES public.login (userid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.occinspection
  OWNER TO sylvia;
```

**Comment by jurplel** [comment]
`OccSpace` and `OccSpaceTypeInspectionDirective` are extremely close. Just a couple of integrator methods still use them--I'll leave that to you.

**Comment by jurplel** [comment]
Why is `OccInspection.notes` now `OccInspection.notespreinspection`?

Do we need general comments and remarks too?

**Comment by edarsow** [comment]
Completed by JURPLEL summer 2021
