### ISSUE TITLE
Migrate payment management pages into new UI from Chen & Chen

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#33]
As discussed at team meeting, NADGIT is gunna give a whack at adopting the new UI from Chen & Chen

**Comment by NADGIT** [comment]
Working on this now!

**Comment by edarsow** [comment]
NADGIT and ECD fixed primefaces library path error with upgrade to most current version of maven.

**Comment by NADGIT** [comment]
I have fully updated feeManage.xhtml to the new UI.

Current list of pages that need to be updated:
1. paymentManage.xhtml
2. feePermissions.xhtml (if the table doesn't fit in the new UI I'll comment on this issue)

**Comment by NADGIT** [comment]
Took pause from this to resolve #46 as it is on the launch milestone's requirements

**Comment by NADGIT** [comment]
#46 is resolved, I'm back on this.

**Comment by NADGIT** [comment]
paymentManage.xhtml is complete! I pulled down the latest commit and it compiles, but I can't log in because my database seems to be missing patches (its dbpatch table only has patches 1,2, and 7.) I'll debug that and then move on to testing the pages I have made so far.

Remaining pages: 
1. feePermissions.xhtml
2. paymentTypeManage.xhtml (forgot about this little guy)

**Comment by NADGIT** [comment]
I fixed the database issue and will continue work on Sunday

**Comment by NADGIT** [comment]
Before I continued converting pages, I wanted to debug what I had thus far. I have finished debugging feeManage.xhtml for OccPeriods and CECases. I'll now debug paymentManage.xhtml.

**Comment by NADGIT** [comment]
paymentManage.xhtml is fully functional! I'll now migrate feePermissions.xhtml and paymentTypeManage.xhtml to the new UI!

**Comment by NADGIT** [comment]
I just finished feePermissions.xhtml and pushed up my work so far. No pull request yet, I still have two more pages to go:

1. paymentTypeManage.xhtml
2. feeTypeManage.xhtml

**Comment by NADGIT** [comment]
Alright! paymentTypeManage.xhtml was a doozy, so I'm already finished with it. All that's left is feeTypeManage.xhtml!

**Comment by NADGIT** [comment]
feeTypeManage.xtml has been migrated to the new UI! All payment pages are using this new interface, and so this issue is complete!
