### ISSUE TITLE
Check with NADGIT on deprecation?

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#36]
Are we using a stack or this?
![image](https://user-images.githubusercontent.com/10214958/82851601-48336200-9ece-11ea-831f-42e2d2d37bc9.png)

**Comment by NADGIT** [comment]
I must have missed that! You can add "inspection" to the NavStack and it should work!

**Comment by NADGIT** [comment]
I've fixed that particular problem in my paymentsUIUpdate branch.
