### ISSUE TITLE
Upgrade FeeManagementBB to use CECasePropertyUnitHeavy

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#40]
Minor tweak discovered by ECD in migrating to unified workflow situation
![image](https://user-images.githubusercontent.com/10214958/82961415-54c9c000-9f8b-11ea-8c54-0df75e0a09c6.png)

**Comment by NADGIT** [comment]
Alright, I'll get that after I address issue 43!

**Comment by NADGIT** [comment]
Alright, I'm making a branch called "paymentsBackendUpdate" where I'll be addressing this issue and #43

**Comment by NADGIT** [comment]
Both FeeManagementBB and PaymentBB now use both CECaseDataHeavy and OccPeriodDataHeavy, so now they have all the necessary information they need! The changes are on paymentBackendUpdate.

**Comment by NADGIT** [comment]
I completely forgot CECasePaymentsBB and the random stuff on OccInspectionBB! I'll get it done quick with some changes. Please view my comment on Issue #43 for more information.
