### ISSUE TITLE
Migrate Payments BB to use PaymentCoordinator

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#43]
See comments in code
![image](https://user-images.githubusercontent.com/10214958/82965899-7761d600-9f97-11ea-90ef-c81953d64991.png)

**Comment by NADGIT** [comment]
Will do! After I finish getting the new UI to work I'll just move right in to migrating stuff to the coordinator.

**Comment by NADGIT** [comment]
Alright, I'm on this now! I've created a branch called paymentsBackEnd update and I'll use it to address this issue and #40!

**Comment by NADGIT** [comment]
Both FeeManagementBB and PaymentBB now use both CECaseDataHeavy and OccPeriodDataHeavy, so now they have all the necessary information they need! The changes are on paymentBackendUpdate.

**Comment by NADGIT** [comment]
I completely forgot CECasePaymentsBB and the random stuff on OccInspectionBB! I'll real quick make sure they're all up-to-date and re-push. From the looks of it they don't use integrators, but I know that the occupancy period fees and payments would not show up on occPeriodPayments.xhtml, so I made some changes and now I'm testing them.
