### ISSUE TITLE
Research mapbox and make a tentative tool platform choice

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#53]
Based on call with WPRDC folks, Leaflet is cool, but MapBox is coolER! Which one should we press forward with to the point of testing a beta?

**Comment by edarsow** [comment]
During call 1 June, the advantages to MapBox over Leaflet are not entirely clear. Moving forward with Leaflet for now.

**Comment by wwalk3** [comment]
Mapbox is a paid platform that charges by map load, Leaflet is a free JS library. Sticking with development in Leaflet for the time being.

**Comment by snapperVibes** [comment]
(essentially closed 22 days ago by wwalk3)
