### ISSUE TITLE
Design UI pattern for Data Label: Data Value system-wide

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#54]
When displaying data about an object in the system, we want a unified styling approach for the label on that data, and the data itself. Example consistency questions from property page:

1. Do we use a : or not? 
2. Do we use a second line for the data regardless of datum length?
3. How should we deal with lists of things?
4. How should the user navigate into an object listed in a related object? e.g. view the profile a Person object listed as connected to a given Event?
![image](https://user-images.githubusercontent.com/10214958/83364092-a4820000-a36c-11ea-91e3-a519c4dbb005.png)

**Comment by Xiaohong-Chen** [comment]
Received Eric! We could design it first and check which one is the best :)

**Comment by Xiaohong-Chen** [comment]
UI pattern for Data Label has been updated. It is under the DataLabelUI branch. I have updated the cogstaff/person/personInfo.xhtml page using new data label UI. Also I created a cogstaff/person/personInfo_sample.xhtml page that you could re-use it for other pages.

**Comment by edarsow** [comment]
Great work, thanks!
