### ISSUE TITLE
Rental boolean flag on unit create is gone/vacation

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#66]
When creating and editing unit lists, there is a column for rental but no button to declare rental intent

![image](https://user-images.githubusercontent.com/10214958/83419762-99be7e00-a3f3-11ea-91be-395aef0c81f7.png)

**Comment by NADGIT** [comment]
That is an error I think I encountered while updating the payments UI. I'll fix this and Issue #78 before I work on the public portal milestone.

**Comment by NADGIT** [comment]
This code is complete, but it's not working yet. I'll comment here when I'm done debugging.

**Comment by NADGIT** [comment]
Whoops didn't mean to hit pin
