### ISSUE TITLE
Table error with the new UI on feeManage.xhtml

### ISSUE THREAD

**Issue by NADGIT** [TechnologyRediscovery/codenforce#72]
![image](https://user-images.githubusercontent.com/46534741/83530561-e1a7d880-a4b9-11ea-9105-fe10f531227a.png)

When the page is first loaded, the table takes up the whole page as you can see in the screenshot, but after hitting one of the mode change buttons (LookUp, Insert, Update, Remove) the table goes back to normal.

**Comment by NADGIT** [comment]
![image](https://user-images.githubusercontent.com/46534741/83689420-02a52200-a5bd-11ea-9493-a34b616f97dd.png)

Here is a similar error on paymentManage.xhtml. Although it looks different, the behavior is the same: clicking on one of the mode buttons brings everything back to normal

**Comment by Xiaohong-Chen** [comment]
It is so strange...I don't have this problem on that. Could you please tell me which branch you are on? So I could download that and try to debug for that?

**Comment by NADGIT** [comment]
My branch is paymentsUIUpdate. I'm all done with my updates on it, and all of the pages under the restricted/cogstaff/money folder have been moved to the new UI. They all have similar problems, but I will be making a new branch from there so go ahead and debug as much as you like! Thanks!

**Comment by Xiaohong-Chen** [comment]
![1](https://user-images.githubusercontent.com/37033896/84403535-d0567e80-abd3-11ea-8017-23488d567ace.png)
I tried to fix that issue. But when I open the page under your branch, it turns to normal...It is so strange..Is that because we use different operating system that cause that issue?

**Comment by edarsow** [comment]
Looks like the Gremlins are infesting NADGIT's computer!
