### ISSUE TITLE
Rework public event list logic in PublicInfoCoordinator

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#73]
Only some events associated with a CECase or an OccPeriod should be released to the public, namely those events whose boolean flag called `disclosetopublic` is true. The `PublicInfoCoordinator` has some commented out code for checking an event list for public release and assembling the list for injection into a `PublicInfoBundleCECase` object for release out to a public user. One reason it is commented out seems to be because public info was dropped as a dev priority during the unification of events between Occ and CE. 

![image](https://user-images.githubusercontent.com/10214958/83533020-0c476080-a4bd-11ea-906f-e7d6cf020d1b.png)

**Comment by NADGIT** [comment]
Working on this issue first!

**Comment by NADGIT** [comment]
I think that commit c787ce7 should fix this issue. I put whatever fields and methods were necessary onto CECasePropertyUnitHeavy, and then fixed up the coordinators.

**Comment by NADGIT** [comment]
I am going to close this issue because I do not think any more problems related to this issue will arise. Besides, as I work on #103 a lot of logic on the PublicInfoCoordinator is going to change.
