### ISSUE TITLE
Eliminate a Unit numbered -1 if a second unit is added

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#78]
Right now, we create a default unit -1 to denote that a property is a single dwelling unit situation. In the unit manager, we'd like to automatically get rid of the -1 unit if a second unit is added. Perhaps this means we automatically ask the user to renumber the -1 if they go to add a second, or perhaps we wait until they've submitted the entire unit renumbered request and then ask: Did user add a unit #1? if not, let's convert -1 to 1 so it no longer shows up as a single unit property.

**Comment by NADGIT** [comment]
I am working on this and Issue #66 before I move on to the public portal

**Comment by NADGIT** [comment]
Though this issue isn't linked to #92 this issue is addressed by it
