### ISSUE TITLE
Review and Organize property external data scripts from Matt

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#90]
The business logic goal of this portion of the codeNforce is to record arbitrary data about a given parcel as stored in the Allegheny County property assessment database (such as last date of sale, sale value, tax status...) every few weeks/months which will allow us to spot changes in that data, which could signal that an owner is not following correct procedures (like getting a property inspection for the sale of a home). 

The way we have implemented steps toward this goal is to write a python script that follows these steps:
1. Ask the database for a list of parcel IDs in a given municipality (from the property table)
2. Retrieve and parse in bs4 appropriate county assessment database pages that contain the data we want to put into the table `propertyexternaldata`
3. Write the scraped data into `propertyexternaldata` (keeping in mind that each time we scrape each property, we'll make a new record in `propertyexternaldata`)
4. Check to see if the data we just wrote to the db is different from the last time we made an entry for a given parcel in `propertyexternaldata`
5. If the data has changed, make an event to log these changes and write it to the `event` table. NOTE that the current version of the scripts from Matt use an outdated version of the `event` table and this should be updated as part of this issue--Now events have a start and end time, not just a timstamp.
6. In order to write an event to document that the external data changed, that property must have a code enforcement case associated with it whose flag called `propertyinfocase` is TRUE. The script should check to see if such a case exists. If the case exists, write the event and include the propertyinfocase's caseid as a foreign key in the `event` table. The event should include a description of what piece of external data changed, such as "property is now delinquent on taxes"
7. If the property doesn't have a propertyinfocase associated with it, create one with a simple INSERT statement into the `cecase` table. The column `cecasepubliccc` can contain a NULL or arbitrary value. Then, using your RETURNING keyword, make an event associated with this fresh property info case.
8. In the even that a property has multiple records in the `cecase` table that are property info cases, attach the even to the case whose date of origin is most recent.

## Notes on external data
For now, we want to see if a property has unpaid taxes or not. We are not trying to parse how much is unpaid, or what type of tax, or when that tax was due, etc. We just want to flag "hey, we've got a tax issue here, go look at the records yourself"

**Comment by edarsow** [comment]
Here is the INSERT for creating an eventcategory suitable for assigning to events related to changes to the propertyexternaldata table
INSERT INTO public.eventcategory(
            categoryid, categorytype, title, description, userdeployable, 
            munideployable, publicdeployable, notifycasemonitors, hidable, 
            icon_iconid, relativeorderwithintype, relativeorderglobal, hosteventdescriptionsuggtext, 
            directive_directiveid, defaultdurationmins)
    VALUES (220, 'PropertyInfoCase'::eventtype, 'Property info related', 'Related to scraping of data from county', FALSE, 
            FALSE, FALSE, TRUE, TRUE, 
            NULL, 0, 0, FALSE, 
            NULL, 0);

**Comment by edarsow** [comment]
SNAPPERS suggested on a call that most of the external data script needs to be completely overhauled.

**Comment by snapperVibes** [comment]
Done awhile ago but never closed.
