### ISSUE TITLE
dataScroller for propertyUnits.xhtml won't AJAX

### ISSUE THREAD

**Issue by NADGIT** [TechnologyRediscovery/codenforce#93]
The propertyUnits.xhtml page uses a dataScroller to show units that fall into two categories, active and inactive. A user is supposed to choose which category of unit they would like to view: active, inactive, or both from a selectOneMenu. After the user selects one of these categories, the dataScroller should refresh (using AJAX) to show only the selected category. In reality, the dataScroller only shows whatever category the initBean defaults it to, and it doesn't change no matter what you select.

However, when I went to report the problem to PrimeFaces, I was supposed to reconstruct the problem from scratch and attach a zip of the reconstruction. To my surprise, the reconstruction worked! I'm unable to find why propertyUnits.xhtml doesn't work and this test file does!

[primefaces-test.zip](https://github.com/TechnologyRediscovery/codenforce/files/4800415/primefaces-test.zip)

For now we've decided to have the list default to showing all units but sorts to show active units first. The dataTable for editing units updates with AJAX just fine, so the page is technically functional, but it doesn't quite meet the requirements for this page. I will be moving on to public portal stuff now, but if anyone wants to help debug this, I'd really appreciate it.

Right now the page is on branch "unitQuickFixes", but will be on recovered once #92 is complete.

**Comment by edarsow** [comment]
Thanks for your slog through this primefaces mess!
