### ISSUE TITLE
Stress test the python scripts for building munis and external data

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#95]
## Connect to production database
Work with Eric one morning to wire up to production database

## Transferring scripts to server
Install file zilla on local machine

## Run external data updates on existing property
Test and document running of python scripts in cron

## Learn about cron jobs
SNAPPERS: try writing a small script locally in bash/python that can document itself running by writing to a file or database. Then setup a cron job to run it perodically locally and verify that it's working. Once you feel comfy with cron locally, you'll be awarded sudo powers on the production server

**Comment by snapperVibes** [comment]
I still haven't set up the cron job, but it certainly passed the stress test (considering it's operational)
