### ISSUE TITLE
Revise OccApplication person assembly

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#98]
See comment on method inside `PersonIntegrator`
![image](https://user-images.githubusercontent.com/10214958/85090018-17370c00-b1b2-11ea-9452-2461258d4e85.png)

**Comment by NADGIT** [comment]
Working on this now so it's ready before I fix #75 !

**Comment by NADGIT** [comment]
I am now working on #111 . This issue might get fixed while working on that. If it does, I'll check back here and comment on my progress!

**Comment by NADGIT** [comment]
You know I came back to this to check on it and I think I did indeed fix this. Marking this as closed
